CREATE TYPE "ModuleKey" AS ENUM ('ADMIN','ITSM','HR','FINANCE','ASSETS','COMPLIANCE');
CREATE TYPE "SubmoduleKey" AS ENUM (
  'ADMIN_SETTINGS','ADMIN_USERS','ADMIN_ROLES_PERMS','ADMIN_SSO','ADMIN_GROUP_MAPPING','ADMIN_AUDIT',
  'ITSM_TICKETS','ITSM_SLA','ITSM_KB','ITSM_AUTOMATIONS','ITSM_REPORTS',
  'HR_EMPLOYEES','HR_EMPLOYEES_PII','HR_ONBOARDING','HR_OFFBOARDING','HR_POLICIES','HR_REPORTS',
  'FINANCE_COST_CENTERS','FINANCE_VENDORS','FINANCE_PURCHASE_REQUESTS','FINANCE_PURCHASE_ORDERS','FINANCE_INVOICES','FINANCE_APPROVALS','FINANCE_ASSETS_LEDGER','FINANCE_REPORTS',
  'ASSETS_EQUIPMENT','ASSETS_ASSIGNMENTS','ASSETS_STOCK','ASSETS_DELIVERIES','ASSETS_MAINTENANCE','ASSETS_REPORTS',
  'COMPLIANCE_RETENTION','COMPLIANCE_ANONYMIZATION','COMPLIANCE_AUDIT_VIEW'
);
CREATE TYPE "AccessLevel" AS ENUM ('READ','WRITE');

CREATE TABLE "user_entitlements" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "module" "ModuleKey" NOT NULL,
  "submodule" "SubmoduleKey" NOT NULL,
  "level" "AccessLevel" NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "user_entitlements_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "user_entitlements_userId_module_submodule_key" ON "user_entitlements"("userId","module","submodule");
CREATE INDEX "user_entitlements_userId_idx" ON "user_entitlements"("userId");
CREATE INDEX "user_entitlements_module_submodule_idx" ON "user_entitlements"("module","submodule");

ALTER TABLE "user_entitlements" ADD CONSTRAINT "user_entitlements_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
