export const PERMISSION_CATALOG = [
  // Platform/Admin
  'platform.admin.view',
  'platform.settings.read',
  'platform.settings.write',
  'platform.authprovider.read',
  'platform.authprovider.write',
  'platform.groupmapping.read',
  'platform.groupmapping.write',
  'platform.users.read',
  'platform.users.write',
  'platform.roles.read',
  'platform.roles.write',
  'audit.read',
  // IAM
  'iam.user.view',
  'iam.user.read',
  'iam.user.write',
  'iam.user.disable',
  'iam.role.read',
  'iam.role.write',
  // ITSM
  'itsm.view',
  'itsm.ticket.read',
  'itsm.ticket.write',
  'itsm.ticket.assign',
  'itsm.ticket.close',
  'itsm.sla.read',
  'itsm.sla.write',
  'itsm.kb.read',
  'itsm.kb.write',
  'itsm.automation.read',
  'itsm.automation.write',
  'itsm.reports.read',
  // Assets
  'assets.view',
  'assets.equipment.read',
  'assets.equipment.write',
  'assets.assignment.read',
  'assets.assignment.write',
  'assets.stock.read',
  'assets.stock.write',
  'assets.delivery.read',
  'assets.delivery.write',
  'assets.maintenance.read',
  'assets.maintenance.write',
  'assets.reports.read',
  // HR
  'hr.view',
  'hr.employee.read',
  'hr.employee.write',
  'hr.employee.read_pii',
  'hr.employee.write_pii',
  'hr.onboarding.read',
  'hr.onboarding.write',
  'hr.offboarding.read',
  'hr.offboarding.write',
  'hr.policy.read',
  'hr.policy.write',
  'hr.ack.read',
  'hr.ack.write',
  'hr.reports.read',
  // Finance
  'finance.view',
  'finance.costcenter.read',
  'finance.costcenter.write',
  'finance.vendor.read',
  'finance.vendor.write',
  'finance.pr.read',
  'finance.pr.write',
  'finance.po.read',
  'finance.po.write',
  'finance.invoice.read',
  'finance.invoice.write',
  'finance.approval.approve',
  'finance.assets.read',
  'finance.assets.write',
  'finance.reports.read',
  // Compliance
  'compliance.view',
  'compliance.retention.read',
  'compliance.retention.write',
  'compliance.anonymize.request',
  'compliance.anonymize.approve',
] as const;

export type PermissionKey = (typeof PERMISSION_CATALOG)[number];
